# Setup
title: Gobs & Gods
description: The tactical RPG going full Goblin mode.
url: https://www.gobsandgods.com

website: https://www.gobsandgods.com
basewebsite: gobsandgods


avatar: /assets/images/logo_large_cropped.png

paginate: 1000
paginate_path: "/blog/page:num"

permalink: /blog/:title:output_ext
cover_image: /assets/images/cartouche_1.jpg


# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec
  - not-pure-poole-license.md

# Optimize Jekyl SEO Tag
twitter:
  username: Goblinou
  card: summary
logo: logo.png
social:
  name: Alexandre Gilotte
  links:
    - https://twitter.com/todo
    - https://www.gobsandgods.com
# google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Google Analytics
google_analytics: G-6VPQPGK69Y


# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Alexandre Gilotte
  url: https://www.gobsandgods.com
#  email: abcd@gmail.com

collections:
  articles:
    output: true
    permalink: /:name:output_ext
    coverimage: steam/store_capsule_header.png
  mobs:
    output: true
    permalink: "/mobs/:name:output_ext"
  enemies:
    output: true
    permalink: "/enemies/:name:output_ext"
  gamerules:
    output: true
    permalink: "/gamerules/:name:output_ext"
  stats:
    output: true
    permalink: "/stats/:name:output_ext"
  derivedstats:
    output: true
    permalink: "/derivedstats/:name:output_ext"
  skills:
    output: true
    permalink: "/skills/:name:output_ext"

defaults:
  - scope:
      path: ""
      type: "gamerules"
    values:
      layout: "gameruleslayout"
  - scope:
      path: ""
      type: "stats"
    values:
      layout: "stats"
  - scope:
      path: ""
      type: "derivedstats"
    values:
      layout: "stats"
  - scope:
      path: ""
      type: "skills"
    values:
      layout: "skills"


